apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
        env: dev
    spec:
      containers:
      - name: tomcat
        image: tomcat:8.0-alpine
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - name: tomcat
          containerPort: 8080
