apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
        env: canary
    spec:
      containers:
      - name: tomcat
        image: tomcat:8.0-alpine
        imagePullPolicy: Always
        ports:
        - name: tomcat
          containerPort: 8080
