apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
        env: canary
    spec:
      containers:
      - name: tomcat
        image: mfabriczy/tomcat-war-deploy:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - name: tomcat
          containerPort: 8080
